#!/bin/bash

recycleBin="$HOME/recyclebin"

validateArgs() {
	if [ "$#" -le 0 ]; then
		echo "$0: no filename is provided"
		exit 1
	fi
}

validateFile() {
	if [ ! -e "$1" ]; then
		echo "$0: file '$1' does not exist"
		exit 2
	fi

	if [ -d "$1" ]; then
		echo "$0: '$1' is a directory, but expect a file"
		exit 3
	fi

	if [ "$(readlink -f "$1")" == "$(readlink -f "$0")" ]; then
		echo "$0: cannot recycle itself"
		exit 4
	fi
}

getRecycleFileName() {
	inodeNumber="$(ls -i "$1" | cut -d' ' -f1)"
	basefilename="$(basename "$1")"
	echo "${basefilename}_${inodeNumber}"
	unset inodeNumber
}

recycleFile() {
	validateFile "$1"
	mv "$1" "$recycleBin/$(getRecycleFileName "$1")"
}

validateArgs "$@"
mkdir -p "$recycleBin"
recycleFile "$1"
