#!/bin/bash

printTestMsgHeader() {
	printf "\033[1;34mTest %s:\033[0m %s\n" "$1" "$2"
}

# 1st arg: test description
# 2nd arg: command to execute
# 3rd arg (optional): expected result; without this, won't check output
testExe() {
	printTestMsgHeader "$1" "$2"
	result="$(eval "$2")"

	if [ "$#" -ge 3 ]; then
		if [ "$result" = "$3" ]; then
			echo -e "\033[1;32mOutput passed\033[0m"
		else
			echo -e "\033[1;31mOuput unmatched\033[0m"
			echo "Expected: $3"
			echo "Got: $result"
			exit 1
		fi
	else
		echo -e "Output: $result"
	fi
}

##############
# Test cases #
##############

testName="No argument"
cmd="bash ./restore"
expectedOutput="./restore: no filename is provided"
testExe "$testName" "$cmd" "$expectedOutput"
