#!/bin/bash

##########
# Set up #
##########

. ./testUtils
. ./exportEnv
clearAll

##############
# Test cases #
##############

testName="No argument"
cmd="bash ./restore"
expectedOutput="./restore: no filename is provided"
testExe "$testName" "$cmd" "$expectedOutput"

testName="Restore a non-existing file"
cmd="bash ./restore non-existing-file_123"
expectedOutput="./restore: file 'non-existing-file_123' does not exist in '$recycleBin'"
testExe "$testName" "$cmd" "$expectedOutput"

testName="Restore a single file"
fileName="testFile"
touch "$fileName"
inodeNumber="$(getInodeNumber "$fileName")"
absPath="$(realpath "$fileName")"
recycleFileName="${fileName}_${inodeNumber}"
echo "$recycleFileName:$absPath" >"$restoreFile"
echo "random-file_72189214:/tmp/non-existing-dir/random-file" >>"$restoreFile" # add a random record
mv "$fileName" "$recycleBin/$recycleFileName"
cmd="bash ./restore $recycleFileName"
testExe "$testName" "$cmd" ''
verifyFileExist "$fileName"
verifyFileNotExist "$recycleBin/$recycleFileName"
checkRestoreInfoNotExist "$recycleFileName" "$absPath"
checkRestoreInfo "random-file_72189214" "/tmp/non-existing-dir/random-file" # check the random record is still there
rm "$fileName"
clearAll
