#!/bin/bash

##########
# Set up #
##########

. ./testUtils
. ./exportEnv
clearAll

##############
# Test cases #
##############

testName="Recycle a single file then restore it"
fileName1="testFile"
touch "$fileName1"
inodeNumber1="$(getInodeNumber "$fileName1")"
absPath1="$(realpath "$fileName1")"
cmd="bash ./recycle \"$fileName1\"; bash ./restore \"${fileName1}_$inodeNumber1\""
testExe "$testName" "$cmd" ''
verifyFileExist "$fileName1"
verifyFileNotExist "$recycleBin/${fileName1}_$inodeNumber1"
checkRestoreInfoNotExist "${fileName1}_$inodeNumber1" "$absPath1"
rm "$fileName1"

testName="Recycle 2 files then restore 1 of them"
fileName1="testFile1"
fileName2="testFile2"
touch "$fileName1" "$fileName2"
inodeNumber1="$(getInodeNumber "$fileName1")"
inodeNumber2="$(getInodeNumber "$fileName2")"
absPath1="$(realpath "$fileName1")"
absPath2="$(realpath "$fileName2")"
cmd="bash ./recycle \"$fileName1\" \"$fileName2\"; bash ./restore ${fileName1}_$inodeNumber1"
testExe "$testName" "$cmd" ''
verifyFileExist "$fileName1"
verifyFileExist "$recycleBin/${fileName2}_$inodeNumber2"
verifyFileNotExist "$recycleBin/${fileName1}_$inodeNumber1"
verifyFileNotExist "$fileName2"
checkRestoreInfoNotExist "${fileName1}_$inodeNumber1" "$absPath1"
checkRestoreInfo "${fileName2}_$inodeNumber2" "$absPath2"
rm "$fileName1"
clearAll

testName="Recycle multiple files using globbing then restore 1 of them"
fileName1="testFile1"
fileName2="testFile2"
touch "$fileName1" "$fileName2"
inodeNumber1="$(getInodeNumber "$fileName1")"
inodeNumber2="$(getInodeNumber "$fileName2")"
absPath1="$(realpath "$fileName1")"
absPath2="$(realpath "$fileName2")"
cmd="bash ./recycle testFile*; bash ./restore ${fileName1}_$inodeNumber1"
testExe "$testName" "$cmd" ''
verifyFileExist "$fileName1"
verifyFileExist "$recycleBin/${fileName2}_$inodeNumber2"
verifyFileNotExist "$recycleBin/${fileName1}_$inodeNumber1"
verifyFileNotExist "$fileName2"
checkRestoreInfoNotExist "${fileName1}_$inodeNumber1" "$absPath1"
checkRestoreInfo "${fileName2}_$inodeNumber2" "$absPath2"
rm "$fileName1"
clearAll

testName="Recycling multiple files won't stop at non-existing file"
fileName1="testFile1"
fileName2="testFile2"
touch "$fileName1" "$fileName2"
inodeNumber1="$(getInodeNumber "$fileName1")"
inodeNumber2="$(getInodeNumber "$fileName2")"
absPath1="$(realpath "$fileName1")"
absPath2="$(realpath "$fileName2")"
cmd="bash ./recycle \"$fileName2\" \"non-existing-file\" \"$fileName1\"; bash ./restore ${fileName1}_$inodeNumber1"
testExe "$testName" "$cmd" \
	"./recycle: file 'non-existing-file' does not exist"
verifyFileExist "$fileName1"
verifyFileExist "$recycleBin/${fileName2}_$inodeNumber2"
verifyFileNotExist "$recycleBin/${fileName1}_$inodeNumber1"
verifyFileNotExist "$fileName2"
checkRestoreInfoNotExist "${fileName1}_$inodeNumber1" "$absPath1"
checkRestoreInfo "${fileName2}_$inodeNumber2" "$absPath2"
rm "$fileName1"
clearAll
