#!/bin/bash

export projectRoot=".."
export restoreFile="$HOME/.restore.info"
export restoreInfoSep=':'
export recycleBin="$HOME/recyclebin"
export tmpDir='tmpDir'
export tmpFile='tmpFile'
export tmpInput='tmpInput'
