#!/bin/bash

##########
# Set up #
##########

cd "$(dirname "$0")" || exit 1
. ./testUtils
. ./exportEnv
clearAll

printf "\033[1;35mStarting Test Suite:\033[0m %s\n" "$0"

##############
# Test cases #
##############

testExe 'no argument' "bash '$projectRoot/recycle'" \
	"$projectRoot/recycle: no filename is provided"
testExe 'provided single non-existing file' "bash '$projectRoot/recycle' non-existing-file" \
	"$projectRoot/recycle: file 'non-existing-file' does not exist"

mkdir -p "$tmpDir"
testExe 'provided single directory' "bash '$projectRoot/recycle' \"$tmpDir\"" \
	"$projectRoot/recycle: '$tmpDir' is a directory, but expect a file"
rmdir "$tmpDir"

testExe 'recycle the recycle script itself' "bash '$projectRoot/recycle' '$projectRoot/recycle'" \
	"$projectRoot/recycle: cannot recycle itself"

touch "$tmpFile"
inodeNumber="$(getInodeNumber "$tmpFile")"
testExe 'recycle single file does put into recyle bin' "bash '$projectRoot/recycle' \"$tmpFile\"" ''
verifyFileExist "$recycleBin/${tmpFile}_$inodeNumber"
clearAll

mkdir -p "$tmpDir"
targetFile="$tmpDir/$tmpFile"
touch "$targetFile"
inodeNumber="$(getInodeNumber "$targetFile")"
testExe 'recycle single file in a directory does put into recyle bin' "bash '$projectRoot/recycle' \"$targetFile\"" ''
verifyFileExist "$recycleBin/${tmpFile}_$inodeNumber"
rmdir "$tmpDir"
clearAll

touch "$tmpFile"
absPath="$(realpath "$tmpFile")"
inodeNumber="$(getInodeNumber "$tmpFile")"
testExe 'recycling file updates .restore.info' "bash '$projectRoot/recycle' \"$tmpFile\"" ''
checkRestoreInfo "${tmpFile}_$inodeNumber" "$absPath"
clearAll

testName='removing multiple files with same filename'
file1="$tmpFile"
file2="$tmpDir/$tmpFile"
mkdir -p "$tmpDir"
touch "$file1" "$file2"
path1="$(realpath "$file1")"
path2="$(realpath "$file2")"
inode1="$(getInodeNumber "$file1")"
inode2="$(getInodeNumber "$file2")"
testExe "$testName" "bash '$projectRoot/recycle' \"$file1\"; bash '$projectRoot/recycle' \"$file2\"" ''
checkRestoreInfo "${tmpFile}_$inode1" "$path1"
checkRestoreInfo "${tmpFile}_$inode2" "$path2"
verifyFileExist "$recycleBin/${tmpFile}_$inode1"
verifyFileExist "$recycleBin/${tmpFile}_$inode2"
rmdir "$tmpDir"
clearAll

testName='exit non-zero if passing invalid option'
fileName="testFile"
touch "$fileName"
inodeNumber="$(getInodeNumber "$fileName")"
absPath="$(realpath "$fileName")"
recycleFileName="${fileName}_${inodeNumber}"
expectedOutput="$projectRoot/recycle: invalid option: -- x"$'\n'"Try '$projectRoot/recycle -h' for more usage."
testExe "$testName" "bash '$projectRoot/recycle' -x \"$fileName\"" "$expectedOutput"
verifyFileExist "$fileName"
verifyFileNotExist "$recycleBin/$recycleFileName"
checkRestoreInfoNotExist "$recycleFileName" "$absPath"
clearAll

testName='confirm recycling when in interactive mode'
fileName1="testFile1"
fileName2="testFile2"
touch "$fileName1" "$fileName2"
inodeNumber1="$(getInodeNumber "$fileName1")"
inodeNumber2="$(getInodeNumber "$fileName2")"
absPath1="$(realpath "$fileName1")"
absPath2="$(realpath "$fileName2")"
recycleFileName1="${fileName1}_${inodeNumber1}"
recycleFileName2="${fileName2}_${inodeNumber2}"
echo "y" >"$tmpInput"
echo "n" >>"$tmpInput"
cmd="bash '$projectRoot/recycle' -i \"$fileName1\" \"$fileName2\" <\"$tmpInput\""
testExe "$testName" "$cmd" ''
verifyFileExist "$recycleBin/$recycleFileName1"
verifyFileExist "$fileName2"
verifyFileNotExist "$fileName1"
verifyFileNotExist "$recycleBin/$recycleFileName2"
checkRestoreInfo "$recycleFileName1" "$absPath1"
checkRestoreInfoNotExist "$recycleFileName2" "$absPath2"
rm "$fileName2"
clearAll

testName='display message in verbose mode'
fileName="testFile"
touch "$fileName"
cmd="bash '$projectRoot/recycle' -v \"$fileName\""
testExe "$testName" "$cmd" "Recycled '$fileName'"
clearAll

testName='recycle in both verbose and interactive mode'
fileName="testFile"
touch "$fileName"
inodeNumber="$(getInodeNumber "$fileName")"
absPath="$(realpath "$fileName")"
recycleFileName="${fileName}_${inodeNumber}"
echo "y" >"$tmpInput"
cmd="bash '$projectRoot/recycle' -vi \"$fileName\" <\"$tmpInput\""
testExe "$testName" "$cmd" "Recycled '$fileName'"
verifyFileExist "$recycleBin/$recycleFileName"
verifyFileNotExist "$fileName"
checkRestoreInfo "$recycleFileName" "$absPath"
clearAll

testName='Recursive recycling'
mkdir -p tmpDir/nestDir1 tmpDir/nestDir2
touch tmpDir/f{1..3} tmpDir/nestDir1/f{1..3} tmpDir/nestDir2/f{1..3}
inodeNumber="$(getInodeNumber tmpDir/nestDir2/f1)"
recycleFileName="f1_$inodeNumber"
realPath="$(realpath tmpDir/nestDir2/f1)"
dirInodeNumber="$(getInodeNumber tmpDir)"
dirRecycleFileName="tmpDir_$dirInodeNumber"
dirRealPath="$(realpath tmpDir)"
cmd="bash '$projectRoot/recycle' -r tmpDir"
testExe "$testName" "$cmd" ''
verifyFileNotExist tmpDir
verifyFileExist "$recycleBin/$recycleFileName"
checkRestoreInfo "$recycleFileName" "$realPath"
verifyFileNotExist "$recycleBin/$dirRecycleFileName"
checkRestoreInfoNotExist "$dirRecycleFileName" "$dirRealPath"
clearAll

testName='should not recycle file whose absolute path contains separator'
touch 'f:'
cmd="bash '$projectRoot/recycle' 'f:'"
expectedOutput="$projectRoot/recycle: can't recycle file 'f:' because its absolute path contains separator '$restoreInfoSep'"
testExe "$testName" "$cmd" "$expectedOutput"
verifyFileExist 'f:'
rm 'f:'
clearAll

testName='can recycle weird file name'
fileName='f+ gogogo!'
touch "$fileName"
inodeNumber="$(getInodeNumber "$fileName")"
recycleFileName="${fileName}_${inodeNumber}"
cmd="bash '$projectRoot/recycle' \"$fileName\""
testExe "$testName" "$cmd" ""
verifyFileNotExist "$fileName"
verifyFileExist "$recycleBin/$recycleFileName"
checkRestoreInfo "$recycleFileName" "$(realpath "$fileName")"
clearAll

testName='should not recycle file in recycle bin'
touch "$recycleBin/testfile"
cmd="bash '$projectRoot/recycle' '$recycleBin/testfile'"
expectedOutput="$projectRoot/recycle: cannot recycle file '$recycleBin/testfile' because it is in the recycle bin"
testExe "$testName" "$cmd" "$expectedOutput"
verifyFileExist "$recycleBin/testfile"
clearAll

testName='help mode should print help message'
cmd="bash '$projectRoot/recycle' -h"
beginLineNum="$(grep -n '^##### BEGIN HELP MESSAGE' "$projectRoot/recycle" | cut -d: -f1)"
endLineNum="$(grep -n '^##### END HELP MESSAGE' "$projectRoot/recycle" | cut -d: -f1)"
expectedOutput="$(head -n "$((endLineNum - 2))" "$projectRoot/recycle" | tail -n "+$((beginLineNum + 2))" | cut -c3-)"
testExe "$testName" "$cmd" "$expectedOutput"

testName="can recycle files with weird names with globbing recurssively"
mkdir -p 'testing directory/nested' 'testing directory/nested2/deep-nested'
touch 'testing directory/nested2/deep-nested/myfile'{1..10}
touch 'testing directory/nested/f'{\!,\@,\#,\$,\%,\^,\&,\*,\(,\),\+,=,\[,\],\{,\},\;,\<,\>,\?,\,}
cmd="bash '$projectRoot/recycle' -r 'testing directory/nested'*"
expectedOutput=""
testExe "$testName" "$cmd" "$expectedOutput"
verifyFileNotExist 'testing directory/nested'
verifyFileNotExist 'testing directory/nested2'
clearAll
